# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [ ]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [ ]:
s = np.array(5)
v = np.array([[5], [-2], [4]])
a = np.array([[1,2,4], [4,5,6], [7,8,9]])
b = np.array([[1,2,3], [4,5,6]])
c = np.array([[1,2], [3,4],[5,6]])
print(f"s = {s}\n\nv = \n {v}\n\na = \n {a}\n\nb = \n {b}\n\nc = \n {c}\n")

s = 5

v = 
 [[ 5]
 [-2]
 [ 4]]

a = 
 [[1 2 4]
 [4 5 6]
 [7 8 9]]

b = 
 [[1 2 3]
 [4 5 6]]

c = 
 [[1 2]
 [3 4]
 [5 6]]



In [ ]:
#type your code here:


s = 5

v =
 [[ 5]
 [-2]
 [ 4]]

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1 2 3]
 [4 5 6]]

C =
 [[1 2]
 [3 4]
 [5 6]]



b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [ ]:
#type your code here:
print(f"type(s) = {type(s)}\n")
print(f"type(v) = {type(v)}\n")
print(f"type(a) = {type(a)}\n")

type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(a) = <class 'numpy.ndarray'>



In [ ]:
#type your code here:


type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(A) = <class 'numpy.ndarray'>



c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [ ]:
#type your code here:
print(f"s.shape = {s.shape}\n")
print(f"v.shape = {v.shape}\n")
print(f"a.shape = {a.shape}\n")
print(f"b.shape = {b.shape}\n")
print(f"c.shape = {c.shape}\n")

s.shape = ()

v.shape = (3, 1)

a.shape = (3, 3)

b.shape = (2, 3)

c.shape = (3, 2)



In [ ]:
#type your code here:


s.shape = ()

v.shape = (3, 1)

A.shape = (3, 3)

B.shape = (2, 3)

C.shape = (3, 2)



d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [ ]:
print(f"A[2, 1] = {a[2, 1]}")
a[2, 1] = 10
print(f"A = \n {a}")

A[2, 1] = 8
A = 
 [[ 1  2  4]
 [ 4  5  6]
 [ 7 10  9]]


In [ ]:
#type your code here:


A[2, 1] =  8

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]



e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [ ]:
print(f"A[:, [1]] = \n {a[:, [1]]}\n")
print(f"B[:, [1]] = \n {b[[1], :]}\n")

A[:, [1]] = 
 [[ 2]
 [ 5]
 [10]]

B[:, [1]] = 
 [[4 5 6]]



In [ ]:
#type your code here:


A[:, [1]] =
 [[ 2]
 [ 5]
 [10]]

B[[1], :] =
 [[4 5 6]]



f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [ ]:
#type your code here:


np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) =
 [0. 0. 0.]

np.zeros(3, 1) =
 [[0.]
 [0.]
 [0.]]

np.zeros(3, 5) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(2, 3) =
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4 5 6 7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


In [ ]:
#type your code here:
print(f"np.eye(4) = \n {np.eye(4)}\n")
print(f"np.zeros(3) = \n {np.zeros(3)}\n")
print(f"np.zeros((3,5)) = \n {np.zeros((3, 5))}\n")
print(f"np.ones((2, 3)) = \n {np.ones((2, 3))}\n")
print(f"np.diag([4, 5, 6, 7]) = \n {np.diag([4, 5, 6, 7])}\n")


np.eye(4) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) = 
 [0. 0. 0.]

np.zeros((3,5)) = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones((2, 3)) = 
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4, 5, 6, 7]) = 
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]



# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [ ]:
v1 = np.array([[1], [2], [7], [4]])
v2 = np.array([[4], [3], [6], [8]])
print(f"v1 = \n {v1}\n")
print(f"v2 = \n {v2}\n")
print(f"v1 + v2 = \n {v1 + v2}\n")
print(f"v1 - v2 = \n {v1 - v2}\n")
print(f"3 * v1 = \n {3*v1}\n")
print(f"v1 / 2 = \n {v1 / 2}\n")

v1 = 
 [[1]
 [2]
 [7]
 [4]]

v2 = 
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 = 
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 = 
 [[-3]
 [-1]
 [ 1]
 [-4]]

3 * v1 = 
 [[ 3]
 [ 6]
 [21]
 [12]]

v1 / 2 = 
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



In [ ]:
#type your code here:


v1 =
 [[1]
 [2]
 [7]
 [4]]

v2 =
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]

3*v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]

v1/2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [ ]:
print(f"Using numpy.dot = \n {np.dot(v1.T, v2)}\n")
print(f"Using numpy.matmul = \n {np.matmul(v1.T, v2)}\n")
print(f"Using @ = \n {v1.T @ (v2)}\n")

Using numpy.dot = 
 [[84]]

Using numpy.matmul = 
 [[84]]

Using @ = 
 [[84]]



In [ ]:
#type your code here:


Using numpy.dot =
 [[84]]

Using numpy.matmul =
 [[84]]

Using @ =
 [[84]]



c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [ ]:
print(f"length of v1 Using numpy.linalg.norm = \n {np.linalg.norm(v1)}\n")
print(f"length of v2 Using numpy.linalg.norm = \n {np.linalg.norm(v2)}\n")
print(f"length of v1 Using the dot product and numpy.sqrt = \n {np.sqrt(np.dot(v1.T, v1))}\n")
print(f"length of v2 Using the dot product and numpy.sqrt = \n {np.sqrt(np.dot(v2.T, v2))}\n")

length of v1 Using numpy.linalg.norm = 
 8.366600265340756

length of v2 Using numpy.linalg.norm = 
 11.180339887498949

length of v1 Using the dot product and numpy.sqrt = 
 [[8.36660027]]

length of v2 Using the dot product and numpy.sqrt = 
 [[11.18033989]]



In [ ]:
#type your code here:


length of v1 Using numpy.linalg.norm =
 8.366600265340756

length of v2 Using numpy.linalg.norm =
 11.180339887498949

length of v1 Using the dot product and numpy.sqrt =
 [[8.36660027]]

length of v2 Using the dot product and numpy.sqrt =
 [[11.18033989]]



d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [ ]:
u = np.array([[3], [2], [-1], [4]])
v = np.array([[1], [-1], [1], [0]])
print(f"u.T @ v = \n {u.T @ v }")

u.T @ v = 
 [[0]]


In [ ]:
#type your code here:


u.T @ v =
 [[0]]



# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [ ]:
u = np.array([[2], [7], [2]])
v = np.array([[8], [2], [4]])
a = np.array([[7, 3, 5], [4, 6, 2]])
b = np.array([[0, 6, 4], [2, 3, 0]])

print(f"u = \n {u}\n")
print(f"v = \n {v}\n")
print(f"v = \n {v}\n")
print(f"A = \n {a}\n")
print(f"B = \n {b}\n")
print(f"A + B = \n {a+b}\n")
print(f"B + A = \n {b+a}\n")
print(f"3A = \n {3 * a}\n")
print(f"6B = \n {6 * b}\n")
print(f"2(3B) = \n {2*(3 * b)}\n")
print(f"6A + 15B = \n {6 * a + 15 * b}\n")
print(f"3(2A + 5B) = \n {3 * ( 2 * a + 5 * b)}\n")
print(f"(3A^T)^T = \n {(3 * a.T).T}\n")


u = 
 [[2]
 [7]
 [2]]

v = 
 [[8]
 [2]
 [4]]

v = 
 [[8]
 [2]
 [4]]

A = 
 [[7 3 5]
 [4 6 2]]

B = 
 [[0 6 4]
 [2 3 0]]

A + B = 
 [[7 9 9]
 [6 9 2]]

B + A = 
 [[7 9 9]
 [6 9 2]]

3A = 
 [[21  9 15]
 [12 18  6]]

6B = 
 [[ 0 36 24]
 [12 18  0]]

2(3B) = 
 [[ 0 36 24]
 [12 18  0]]

6A + 15B = 
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) = 
 [[ 42 108  90]
 [ 54  81  12]]

(3A^T)^T = 
 [[21  9 15]
 [12 18  6]]



In [ ]:
#type your code here:


u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]


 (3A^T)^T = 
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [ ]:
print(f"Au + Av = \n {a @ u + a @ v}\n")
print(f"A(u + v) = \n {a @(u + v)}\n")
print(f"(A + B)u = \n {(a + b) @ u}\n")
print(f"Au + Bu = \n {a @ u + b @ u}\n")
print(f"A(3u) = \n {a @ ( 3 * u)}\n")
print(f"3A(u) = \n {3 * a @ u}\n")

Au + Av = 
 [[127]
 [106]]

A(u + v) = 
 [[127]
 [106]]

(A + B)u = 
 [[95]
 [79]]

Au + Bu = 
 [[95]
 [79]]

A(3u) = 
 [[135]
 [162]]

3A(u) = 
 [[135]
 [162]]



In [ ]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries

In [ ]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[4. 7. 2. 4.]
 [5. 5. 1. 7.]
 [7. 7. 1. 3.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix).

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [ ]:
#type your code here:
r = A
r[0, :] = r[0, :] / r[0, 0]
r[1, :] = r[1, :] - r[0, :] * r[1, 0]
r[2, :] = r[2, :] - r[2, 0] * r[0, :]
print(r)

[[ 1.    1.75  0.5   1.  ]
 [ 0.   -3.75 -1.5   2.  ]
 [ 0.   -5.25 -2.5  -4.  ]]


Matrix([
[1.0,  1.75,  0.5,  1.0],
[  0, -3.75, -1.5,  2.0],
[  0, -5.25, -2.5, -4.0]])

#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [ ]:
r[1, :] = r[1, :] / r[1, 1]
r[0, :] = r[0, :] - r[1, :] * r[0, 1]
r[2, :] = r[2, :] - r[1, :] * r[2, 1]
r

array([[-0.75      ,  0.        ,  0.15      , -1.45      ],
       [-0.        ,  1.        ,  0.4       , -0.53333333],
       [ 0.        ,  0.        , -0.4       , -6.8       ]])

#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [ ]:
#type your code here:
r[2, :] = r[2, :] / r[2, 2]
r[0, :] = r[0, :] - r[2, :] * r[0, 2]
r[1, :] = r[1, :] - r[2, :] * r[1, 2]
r

array([[-0.75      ,  0.        ,  0.        , -4.        ],
       [ 0.        ,  1.        ,  0.        , -7.33333333],
       [-0.        , -0.        ,  1.        , 17.        ]])

#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [ ]:
M = sym.Matrix(A)
M_rref = M.rref()
R = np.array((M_rref[0])).astype(np.float64)
print(f"rank = \n {np.linalg.matrix_rank(R)}")
print(f"The Row echelon form of matrix M\n {R}")

rank = 
 3
The Row echelon form of matrix M
 [[ 1.          0.          0.          5.33333333]
 [ 0.          1.          0.         -7.33333333]
 [ 0.          0.          1.         17.        ]]


In [ ]:
#type your code here:

# Use sympy.rref() method



 rank = 
 3

 The Row echelon form of matrix M 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$.

2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [ ]:
def dot_product(a, b):
    if a.ndim == 1 and b.ndim == 1:
        res = 0
        assert len(a) == len(b), "Vectors must be of the same lenght"
        for i in range(len(a)):
            res += a[i] * b[i]
        return res
    elif a.ndim > 1 and b.ndim > 1:
        m, x = a.shape
        y, p = b.shape
        assert x == y, "Matries inner dimention must match"
        c = np.zeros((m, p))
    #####################################
        for i in range(m):
            for j in range(p):
                c[i, j] = dot_product(a[i, :], b[:, j])
        return c
    elif a.ndim > 1 and b.ndim == 1:
        m, x = a.shape
        y = b.shape[0]
        assert x == y, "Matries inner dimention must match"
        c = np.zeros((m))
    #####################################
        for i in range(m):
                c[i] = dot_product(a[i, :], b)
        return c
    elif b.ndim > 1 and a.ndim == 1:
        m = a.shape[0]
        y, p = b.shape
        assert m == y, "Vector and Matrix inner dimention must match"
        c = np.zeros((p))
        for i in range(p):
            c[i] = dot_product(a, b[:, i])
        return  c


In [ ]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        for j in range(p):
            C[i, j] = dot_product(A[i, :], B[:, j])
    ########################################################
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(p):
        C[:, i] = dot_product(A, B[:,i])

    ########################################################
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        C[i, :] = dot_product(A[i,:], B)

    ########################################################
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(n):
        tmp = dot_product(A[:, [i]], B[[i], :])
        C = C +  tmp

    ########################################################
    return C

In [ ]:

# def check_dimension(A, B):
#     return A.shape[1] == B.shape[0]

# def mat_mul_standard(A, B):
#     if not check_dimension(A, B):
#         raise Exception('Dimensions aren\'t consistant')

#     m, n = A.shape
#     n, p = B.shape

#     C = np.zeros((m, p))
#     ################type your code here#####################
#     for i in range(m):
#         for j in range(p):
#             C[i, j] = A[i, :].dot(B[:, j])
#     # C = A.dot(B)

#     ########################################################
#     return C


# def mat_mul_columns(A, B):
#     if not check_dimension(A, B):
#         raise Exception('Dimensions aren\'t consistant')

#     m, n = A.shape
#     n, p = B.shape

#     C = np.zeros((m, p))
#     ################type your code here#####################
#     for i in range(p):
#         C[:, i] = A.dot(B[:,i])

#     ########################################################
#     return C

# def mat_mul_rows(A, B):
#     if not check_dimension(A, B):
#         raise Exception('Dimensions aren\'t consistant')

#     m, n = A.shape
#     n, p = B.shape

#     C = np.zeros((m, p))
#     ################type your code here#####################
#     for i in range(m):
#         C[i, :] = A[i,:].dot(B)

#     ########################################################
#     return C



# def mat_mul_column_times_row(A, B):
#     if not check_dimension(A, B):
#         raise Exception('Dimensions aren\'t consistant')

#     m, n = A.shape
#     n, p = B.shape

#     C = np.zeros((m, p))
#     ################type your code here#####################
#     for i in range(n):
#         tmp = A[:, [i]].dot(B[[i], :])
#         C = C +  tmp

#     ########################################################
#     return C

In [ ]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

# A = np.fix((10*(np.random.rand(3, 3))))
# B = np.fix((10*(np.random.rand(3, 3))))
A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [ ]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5884. 5559. 5764. ... 5983. 5328. 5794.]
 [6596. 5996. 6484. ... 5945. 5853. 6458.]
 [5928. 5847. 6072. ... 5641. 5386. 5952.]
 ...
 [5587. 5096. 5924. ... 5516. 5055. 5553.]
 [6367. 6363. 6531. ... 6290. 6040. 6731.]
 [5547. 5680. 6013. ... 5726. 5395. 6070.]]
CPU times: user 5.33 ms, sys: 2.99 ms, total: 8.32 ms
Wall time: 5.52 ms


In [ ]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5884. 5559. 5764. ... 5983. 5328. 5794.]
 [6596. 5996. 6484. ... 5945. 5853. 6458.]
 [5928. 5847. 6072. ... 5641. 5386. 5952.]
 ...
 [5587. 5096. 5924. ... 5516. 5055. 5553.]
 [6367. 6363. 6531. ... 6290. 6040. 6731.]
 [5547. 5680. 6013. ... 5726. 5395. 6070.]]
CPU times: user 6.3 s, sys: 102 ms, total: 6.4 s
Wall time: 6.36 s


In [ ]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5884. 5559. 5764. ... 5983. 5328. 5794.]
 [6596. 5996. 6484. ... 5945. 5853. 6458.]
 [5928. 5847. 6072. ... 5641. 5386. 5952.]
 ...
 [5587. 5096. 5924. ... 5516. 5055. 5553.]
 [6367. 6363. 6531. ... 6290. 6040. 6731.]
 [5547. 5680. 6013. ... 5726. 5395. 6070.]]
CPU times: user 5.88 s, sys: 16 ms, total: 5.9 s
Wall time: 5.92 s


In [ ]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5884. 5559. 5764. ... 5983. 5328. 5794.]
 [6596. 5996. 6484. ... 5945. 5853. 6458.]
 [5928. 5847. 6072. ... 5641. 5386. 5952.]
 ...
 [5587. 5096. 5924. ... 5516. 5055. 5553.]
 [6367. 6363. 6531. ... 6290. 6040. 6731.]
 [5547. 5680. 6013. ... 5726. 5395. 6070.]]
CPU times: user 5.92 s, sys: 15.8 ms, total: 5.93 s
Wall time: 5.97 s


In [ ]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5884. 5559. 5764. ... 5983. 5328. 5794.]
 [6596. 5996. 6484. ... 5945. 5853. 6458.]
 [5928. 5847. 6072. ... 5641. 5386. 5952.]
 ...
 [5587. 5096. 5924. ... 5516. 5055. 5553.]
 [6367. 6363. 6531. ... 6290. 6040. 6731.]
 [5547. 5680. 6013. ... 5726. 5395. 6070.]]
CPU times: user 28.7 s, sys: 67.7 ms, total: 28.8 s
Wall time: 28.9 s
