# Lab 5: PCA Using Eigenvectors and Singular Value Decomposition

# First: you should run this cell

In [ ]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

# Question 1 : PCA Using Eigenvectors

#### Create a matrix contains the following data

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **Sample #1** | 1 | 2 | 3 | 4 |
| **Sample #2** | 5 | 5 | 6 | 7 |
| **Sample #3**| 1 | 4 | 2 | 3 |
| **Sample #4**| 5 | 3 | 2 | 1 |
| **Sample #5**| 8 | 1 | 2 | 2 |

In [ ]:
M = np.array([[1,2,3,4],
              [5,5,6,7],
              [1,4,2,3],
              [5,3,2,1],
              [8,1,2,2]])
print('M = \n{}\n'.format(M))

M = 
[[1 2 3 4]
 [5 5 6 7]
 [1 4 2 3]
 [5 3 2 1]
 [8 1 2 2]]



### Step 1: Standardize the dataset.
- Calculate data mean for each feature.
- Calculate data standard deviation for each feature.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **$\mu$** | 4 | 3 | 3 | 3.4 |
| **$\sigma$**| 3 | 1.58114 | 1.73205 | 2.30217 |


- Standardize the data.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **Sample #1** | -1.         | -0.63245553 |  0.         |  0.26062335 |
| **Sample #2** |  0.33333333 | 1.26491106 |  1.73205081 |  1.56374007 |
| **Sample #3** | -1.         | 0.63245553 | -0.57735027 | -0.1737489  |
| **Sample #4** |  0.33333333 | 0.         | -0.57735027 | -1.04249338 |
| **Sample #5** |  1.33333333 | -1.26491106 | -0.57735027 | -0.60812114 |




In [ ]:
mean = M.mean(axis=0)
print("-"* 20, "M", "-" * 20, f"\n {M}\n", "-" * 40, "\n")
print("-"* 20, "Data mean", "-" * 20, f"\n {mean}\n", "-" * 40, "\n")
std = M.std(axis=0)
print("-"* 20, "Data standard deviation", "-" * 20, f"\n {std}\n", "-" * 40, "\n")
X = (M - mean) / std
print("-"* 20, "X", "-" * 20, f"\n {X}\n", "-" * 40, "\n")

-------------------- M -------------------- 
 [[1 2 3 4]
 [5 5 6 7]
 [1 4 2 3]
 [5 3 2 1]
 [8 1 2 2]]
 ---------------------------------------- 

-------------------- Data mean -------------------- 
 [4.  3.  3.  3.4]
 ---------------------------------------- 

-------------------- Data standard deviation -------------------- 
 [2.68328157 1.41421356 1.54919334 2.05912603]
 ---------------------------------------- 

-------------------- X -------------------- 
 [[-1.11803399 -0.70710678  0.          0.29138576]
 [ 0.372678    1.41421356  1.93649167  1.74831455]
 [-1.11803399  0.70710678 -0.64549722 -0.19425717]
 [ 0.372678    0.         -0.64549722 -1.16554303]
 [ 1.49071198 -1.41421356 -0.64549722 -0.6799001 ]]
 ---------------------------------------- 



In [ ]:
#type your code here:


### Step 2: Calculate the covariance matrix for the features in the dataset.

-  Calculate covariance matrix using the formula: $C = \frac{X^TX}{n-1}$,  where $n$ is the number of data points.
##### Note: This formula is used because the data has <b>zero</b> mean and <b>1</b> standard deviation.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
|**Feature #1** |  1.         | -0.31622777 |  0.04811252 | -0.18098843 |
|**Feature #2** | -0.31622777 |  1.         |  0.63900965 |  0.61812254 |
|**Feature #3** |  0.04811252 |  0.63900965 |  1.         |  0.94044349 |
|**Feature #4** | -0.18098843 |  0.61812254 |  0.94044349 |  1.         |

In [ ]:
cov = (X.T.dot(X)) / (len(X) - 1)
print("-"* 20, "cov(C)", "-" * 20, f"\n {cov}\n", "-" * 40, "\n")

-------------------- cov(C) -------------------- 
 [[ 1.25       -0.39528471  0.06014065 -0.22623554]
 [-0.39528471  1.25        0.79876206  0.77265317]
 [ 0.06014065  0.79876206  1.25        1.17555437]
 [-0.22623554  0.77265317  1.17555437  1.25      ]]
 ---------------------------------------- 



In [ ]:
#type your code here:


C = 
[[ 1.         -0.31622777  0.04811252 -0.18098843]
 [-0.31622777  1.          0.63900965  0.61812254]
 [ 0.04811252  0.63900965  1.          0.94044349]
 [-0.18098843  0.61812254  0.94044349  1.        ]]



### Step 3: Calculate the eigenvalues and eigenvectors for the covariance matrix and sort eigenvalues and their corresponding eigenvectors.

- Find eigen values and the corresponding eigen vectors for the covariance matrix
- Calculate how much variance captured in each component. $\frac{\lambda_j}{\sum_{k=1}^{m}\lambda_k}$, where $m$ is the number of features.

| Eigenvector #1 | Eigenvector #2 | Eigenvector #3 | Eigenvector #4 |
| --- | --- | --- | --- |
| 0.16195986 | -0.91705888 | -0.30707099 |  0.19616173 |
|-0.52404813 |  0.20692161 | -0.81731886 |  0.12061043 |
|-0.58589647 | -0.3205394  |  0.1882497  | -0.72009851 |
|-0.59654663 | -0.11593512 |  0.44973251 |  0.65454704 |

In [ ]:
eValues, eVectors = np.linalg.eig(cov)
idx = np.argsort(eValues)[::-1]
eValues, eVectors = eValues[idx], eVectors[idx]
print("-"* 20, "Eigenvalues ", "-" * 20, f"\n {eValues}\n", "-" * 40, "\n")
print("-"* 20, "Percentage of variance  ", "-" * 20, f"\n {eValues / np.sum(eValues)}\n", "-" * 40, "\n")
print("-"* 20, "Eigenvectors  ", "-" * 20, f"\n {eVectors}\n", "-" * 40, "\n")
np.linalg.norm(eVectors[:,3])

-------------------- Eigenvalues  -------------------- 
 [3.14474155 1.33161063 0.4923588  0.03128901]
 ---------------------------------------- 

-------------------- Percentage of variance   -------------------- 
 [0.62894831 0.26632213 0.09847176 0.0062578 ]
 ---------------------------------------- 

-------------------- Eigenvectors   -------------------- 
 [[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]
 ---------------------------------------- 



1.0

In [ ]:
#type your code here:


Eigenvalues = 
[2.51579324 1.0652885  0.39388704 0.02503121]
---------------------------------------------
Percentage of variance = 
 [0.62894831 0.26632213 0.09847176 0.0062578 ]
---------------------------------------------
Eigenvectors = 
[[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]


### Step 4: Pick $k$ eigenvalues and form a matrix of eigenvectors.

- Select the first two eigen vectors

In [ ]:
eig_vecs_2  = X @ eVectors[:, :2]
print("-"* 20, "eig_vecs_2", "-" * 20, f"\n {eig_vecs_2}\n", "-" * 40, "\n")

-------------------- eig_vecs_2 -------------------- 
 [[ 1.56561741e-02  8.45205482e-01]
 [-2.85829190e+00 -8.72549250e-01]
 [-5.75566043e-02  1.40104719e+00]
 [ 1.13385419e+00  2.66995807e-04]
 [ 1.76633814e+00 -1.37397042e+00]]
 ---------------------------------------- 



In [ ]:
#type your code here:


eig_vecs_2 = 
 [[ 0.16195986 -0.91705888]
 [-0.52404813  0.20692161]
 [-0.58589647 -0.3205394 ]
 [-0.59654663 -0.11593512]]


### Step 5:Transform the standardized matrix matrix.

- `M_transformed = X @ eig_vecs_2`

In [ ]:
X.shape , eig_vecs_2.shape

((5, 4), (5, 2))

In [ ]:
M_transformed = X.T @ eig_vecs_2
print("-"* 20, "M_transformed", "-" * 20, f"\n {M_transformed}\n", "-" * 40, "\n")

-------------------- M_transformed -------------------- 
 [[ 2.03728755 -4.88466141]
 [-6.59198377  1.10215606]
 [-7.36997193 -1.70733468]
 [-7.50393989 -0.61752174]]
 ---------------------------------------- 



In [ ]:
#type your code here:


M_transformed = 
 [[ 0.01400331  0.75597476]
 [-2.55653399 -0.78043177]
 [-0.05148019  1.2531347 ]
 [ 1.01415002  0.00023881]
 [ 1.57986086 -1.2289165 ]]


# Question 2 : Singular Value Decomposition (SVD)

#### For a square (real) matrices of size $(n,n)$ can be "eigendecomposed"  :
$$A = V . Diag(\Lambda). V^T$$

With $V$: eigenvectors
; $Diag(\Lambda)$: eigenvalues (on the diagonal).

#### But for a non square  of size $(n,m) (n \neq m)$, we need to use the  Singular Value Decomposition (SVD)

- Let $A $ be a matrix of size $(n,m)$ with  $n \neq m$ the SVD of A is defined by:

$$A= U . S . V^T $$

Where:
 $U$: size $(n,n)$, square;
 $V$: size $(m,m)$, square;
 $S$: size $(n,m)$, rectanguler if $n \neq m$

- The values on the "diagonal" of $S$ are called: **singular values**. The singular values are generally sorted by decreasing order.
- The columns of $U$ are called the **left-singular vectors**
- The columns of $V$ are called the **right-singular vectors**

#### (a) For the matrix $A$, find the SVD

In [ ]:
A = np.array([[1, 1, 1],
              [3, 4, 5],
              [4, 4, 4],
              [4, 5, 4]
              ])
rank = np.linalg.matrix_rank(A)
n, m = A.shape
print("n = ", n)
print("---------------------------------------------")
print("m = ", m)
print("---------------------------------------------")
print("rank = ", rank)
print("---------------------------------------------")
print("A = \n", A)

n =  4
---------------------------------------------
m =  3
---------------------------------------------
rank =  3
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]


- `U, s, VT = np.linalg.svd(A, full_matrices=True)`

In [ ]:
U, s, VT = np.linalg.svd(A, full_matrices=True)
print("-"* 20, "U", "-" * 20, f"\n {U}\n", "-" * 40, "\n")
print("-"* 20, "s", "-" * 20, f"\n {s}\n", "-" * 40, "\n")
print("-"* 20, "VT", "-" * 20, f"\n {VT}\n", "-" * 40, "\n")

-------------------- U -------------------- 
 [[-1.38201662e-01  6.54749524e-02 -1.88246808e-01 -9.70142500e-01]
 [-5.59976765e-01 -8.18823566e-01  1.26309104e-01 -1.27675648e-15]
 [-5.52806648e-01  2.61899810e-01 -7.52987231e-01  2.42535625e-01]
 [-6.01440881e-01  5.06605850e-01  6.17753494e-01 -1.44328993e-15]]
 ---------------------------------------- 

-------------------- s -------------------- 
 [12.49789499  1.23098537  0.53599988]
 ---------------------------------------- 

-------------------- VT -------------------- 
 [[-0.51489647 -0.60782554 -0.60450785]
 [ 0.55486191  0.30122956 -0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]
 ---------------------------------------- 



In [ ]:
#type your code here:


U:
 [[-0.13820166 -0.06547495 -0.18824681 -0.9701425 ]
 [-0.55997677  0.81882357  0.1263091  -0.        ]
 [-0.55280665 -0.26189981 -0.75298723  0.24253563]
 [-0.60144088 -0.50660585  0.61775349 -0.        ]]
---------------------------------------------
s:
 [12.49789499  1.23098537  0.53599988]
---------------------------------------------
VT:
 [[-0.51489647 -0.60782554 -0.60450785]
 [-0.55486191 -0.30122956  0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]


- Construct the matrix $A$ from the SVD:
$$A= U . S . V^T $$
Where:
 $U$: size $(n,n)$, square;
 $V$: size $(m,m)$, square;
 $S$: size $(n,m)$, rectanguler if $n \neq m$

In [ ]:
U.shape, np.diag(s).shape, VT.shape

((4, 4), (3, 3), (3, 3))

In [ ]:
S = np.diag(s)
S = np.vstack([S, np.zeros((1,3))])
print("-"* 20, "U", "-" * 20, f"\n {U}\n", "-" * 40, "\n")
print("-"* 20, "S", "-" * 20, f"\n {S}\n", "-" * 40, "\n")
print("-"* 20, "VT", "-" * 20, f"\n {VT}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
print("-"* 20, "U @ S @ VT", "-" * 20, f"\n {(U @ S) @ VT}\n", "-" * 40, "\n")

-------------------- U -------------------- 
 [[-1.38201662e-01  6.54749524e-02 -1.88246808e-01 -9.70142500e-01]
 [-5.59976765e-01 -8.18823566e-01  1.26309104e-01 -1.27675648e-15]
 [-5.52806648e-01  2.61899810e-01 -7.52987231e-01  2.42535625e-01]
 [-6.01440881e-01  5.06605850e-01  6.17753494e-01 -1.44328993e-15]]
 ---------------------------------------- 

-------------------- S -------------------- 
 [[12.49789499  0.          0.        ]
 [ 0.          1.23098537  0.        ]
 [ 0.          0.          0.53599988]
 [ 0.          0.          0.        ]]
 ---------------------------------------- 

-------------------- VT -------------------- 
 [[-0.51489647 -0.60782554 -0.60450785]
 [ 0.55486191  0.30122956 -0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
 ---------------------------------------- 

-------------------- U @ S @ VT -------------------- 
 [[1

In [ ]:
#type your code here:


U=
 [[-0.13820166 -0.06547495 -0.18824681 -0.9701425 ]
 [-0.55997677  0.81882357  0.1263091  -0.        ]
 [-0.55280665 -0.26189981 -0.75298723  0.24253563]
 [-0.60144088 -0.50660585  0.61775349 -0.        ]]
---------------------------------------------
S=
 [[12.49789499  0.          0.        ]
 [ 0.          1.23098537  0.        ]
 [ 0.          0.          0.53599988]
 [ 0.          0.          0.        ]]
---------------------------------------------
VT=
 [[-0.51489647 -0.60782554 -0.60450785]
 [-0.55486191 -0.30122956  0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
U @ S @ VT=
 [[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]


#### $k$-rank approximation

- Construct the matrix $\tilde{A}$ using **$k$-rank approximation**.
- Calculate the approximation error using frobenius norm.

$$\tilde{A}= \tilde{U} . \tilde{S} . \tilde{V}^T $$
Where:
 $\tilde{U}$: size $(n,k)$,
  $\tilde{S}$: size $(k,k)$,
 $\tilde{V}$: size $(k,m)$;


In [ ]:
k = 3
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 3
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]
 ---------------------------------------- 

-------------------- A_tildle_rank -------------------- 
 3
 ---------------------------------------- 

-------------------- error -------------------- 
 7.360200912728141e-15
 ---------------------------------------- 



In [ ]:
#type your code here:


---------------------------------------------
k =
 3
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
A_tilde = 
 [[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]
---------------------------------------------
A_tilde_rank = 
 3
---------------------------------------------
error = 
 8.350323853034144e-15


In [ ]:
k = 2
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 2
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[0.93406572 1.07413313 0.98162029]
 [3.04424033 3.95025845 5.01233235]
 [3.73626287 4.29653251 3.92648116]
 [4.21637091 4.75672364 4.06031513]]
 ---------------------------------------- 

-------------------- A_tildle_rank -------------------- 
 2
 ---------------------------------------- 

-------------------- error -------------------- 
 0.5359998808909961
 ---------------------------------------- 



In [ ]:
#type your code here:


---------------------------------------------
k =
 2
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
A_tilde = 
 [[0.93406572 1.07413313 0.98162029]
 [3.04424033 3.95025845 5.01233235]
 [3.73626287 4.29653251 3.92648116]
 [4.21637091 4.75672364 4.06031513]]
---------------------------------------------
A_tilde_rank = 
 2
---------------------------------------------
error = 
 0.535999880890996


In [ ]:
k = 1
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 1
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[0.88934457 1.04985441 1.044124  ]
 [3.60351884 4.25388574 4.2306668 ]
 [3.55737826 4.19941766 4.17649602]
 [3.87034549 4.56886954 4.54393133]]
 ---------------------------------------- 

-------------------- A_tildle_rank -------------------- 
 1
 ---------------------------------------- 

-------------------- error -------------------- 
 1.3426171667971218
 ---------------------------------------- 



In [ ]:
#type your code here:


---------------------------------------------
k =
 1
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]
---------------------------------------------
A_tilde = 
 [[0.88934457 1.04985441 1.044124  ]
 [3.60351884 4.25388574 4.2306668 ]
 [3.55737826 4.19941766 4.17649602]
 [3.87034549 4.56886954 4.54393133]]
---------------------------------------------
A_tilde_rank = 
 1
---------------------------------------------
error = 
 1.3426171667971218


#### (b) Repeat the previous steps in (a) for the following matrix

In [ ]:
A = np.array([[1, 1, 1, 0, 1],
              [3, 4, 5, 1, 0],
              [4, 4, 4, 0, 1],
              [4, 5, 4, 1, 1],
              [4, 6, 4, 0, 1],
              [4, 7, 4, 1, 1],
              [4, 8, 4, 0, 1],
              [4, 9, 4, 1, 0],
              ])

n, m=A.shape
print("n= ", n)
print("---------------------------------------------")
print("m = ", m)
print("---------------------------------------------")
print("rank = ", rank)
print("---------------------------------------------")
print("A = \n", A)

n=  8
---------------------------------------------
m =  5
---------------------------------------------
rank =  3
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]


In [ ]:
U, s, VT = np.linalg.svd(A, full_matrices=True)
print("-"* 20, "U", "-" * 20, f"\n {U}\n", "-" * 40, "\n")
print("-"* 20, "s", "-" * 20, f"\n {s}\n", "-" * 40, "\n")
print("-"* 20, "VT", "-" * 20, f"\n {VT}\n", "-" * 40, "\n")

-------------------- U -------------------- 
 [[-7.79647196e-02  1.53017197e-01 -3.53029757e-01  2.28776787e-01
   5.76962582e-01 -4.21743952e-01 -3.46284476e-01  4.03573651e-01]
 [-3.00949266e-01  5.20610942e-01  6.79399402e-01 -2.51753516e-01
   3.36794308e-01 -5.55111512e-16 -3.05311332e-16  4.02455846e-16]
 [-3.00576700e-01  4.63617867e-01 -3.27397215e-01 -2.20288109e-01
  -4.89461080e-01  1.17390447e-01  1.11468386e-01  5.22703038e-01]
 [-3.36545919e-01  2.83109965e-01 -4.23712681e-02  5.82223875e-01
  -2.17668378e-01 -4.10437192e-01  2.98471402e-01 -4.01101281e-01]
 [-3.66610234e-01  7.50478785e-02 -3.01628285e-01 -3.07975353e-01
  -6.53503597e-02  7.02203098e-02 -6.07979292e-01 -5.43411383e-01]
 [-4.02579453e-01 -1.05460024e-01 -1.66023380e-02  4.94536632e-01
   2.06442342e-01  7.26745156e-01 -3.87580446e-02  9.84210424e-02]
 [-4.32643767e-01 -3.13522110e-01 -2.75859355e-01 -3.95662596e-01
   3.58760361e-01 -8.21747690e-02  5.83082026e-01 -8.01850680e-02]
 [-4.64852261e-01 -5.43

In [ ]:
#type your code here:


U:
 [[-0.07796472  0.1530172  -0.35302976  0.22877679 -0.57696258 -0.38937491
  -0.44740288  0.3299552 ]
 [-0.30094927  0.52061094  0.6793994  -0.25175352 -0.33679431 -0.
  -0.          0.        ]
 [-0.3005767   0.46361787 -0.32739721 -0.22028811  0.48946108  0.15935356
  -0.02773061  0.52274434]
 [-0.33654592  0.28310997 -0.04237127  0.58222388  0.21766838 -0.4401089
   0.38618031 -0.2749455 ]
 [-0.36661023  0.07504788 -0.30162828 -0.30797535  0.06535036  0.02405806
  -0.44256981 -0.68805437]
 [-0.40257945 -0.10546002 -0.01660234  0.49453663 -0.20644234  0.73214008
  -0.05062814  0.0274791 ]
 [-0.43264377 -0.31352211 -0.27585935 -0.3956626  -0.35876036 -0.08606789
   0.58215114  0.08282124]
 [-0.46485226 -0.54351365  0.37074053  0.0283843   0.30188407 -0.29203118
  -0.33555216  0.2474664 ]]
---------------------------------------------
s:
 [22.57699942  3.35144935  1.90842851  1.00414786  0.62966044]
---------------------------------------------
VT:
 [[-0.45161209 -0.74541953 -0.4782

In [ ]:
#type your code here:
S = np.diag(s)
shape0 = int(np.abs(U.shape[0] - VT.shape[0]))
shape1 = int(VT.shape[1])
S = np.vstack([S, np.zeros((shape0, shape1))])
# S = np.vstack([S, np.zeros(3, 5)])
print("-"* 20, "U", "-" * 20, f"\n {U}\n", "-" * 40, "\n")
print("-"* 20, "S", "-" * 20, f"\n {S}\n", "-" * 40, "\n")
print("-"* 20, "VT", "-" * 20, f"\n {VT}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
print("-"* 20, "U @ S @ VT", "-" * 20, f"\n {(U @ S) @ VT}\n", "-" * 40, "\n")

-------------------- U -------------------- 
 [[-7.79647196e-02  1.53017197e-01 -3.53029757e-01  2.28776787e-01
   5.76962582e-01 -4.21743952e-01 -3.46284476e-01  4.03573651e-01]
 [-3.00949266e-01  5.20610942e-01  6.79399402e-01 -2.51753516e-01
   3.36794308e-01 -5.55111512e-16 -3.05311332e-16  4.02455846e-16]
 [-3.00576700e-01  4.63617867e-01 -3.27397215e-01 -2.20288109e-01
  -4.89461080e-01  1.17390447e-01  1.11468386e-01  5.22703038e-01]
 [-3.36545919e-01  2.83109965e-01 -4.23712681e-02  5.82223875e-01
  -2.17668378e-01 -4.10437192e-01  2.98471402e-01 -4.01101281e-01]
 [-3.66610234e-01  7.50478785e-02 -3.01628285e-01 -3.07975353e-01
  -6.53503597e-02  7.02203098e-02 -6.07979292e-01 -5.43411383e-01]
 [-4.02579453e-01 -1.05460024e-01 -1.66023380e-02  4.94536632e-01
   2.06442342e-01  7.26745156e-01 -3.87580446e-02  9.84210424e-02]
 [-4.32643767e-01 -3.13522110e-01 -2.75859355e-01 -3.95662596e-01
   3.58760361e-01 -8.21747690e-02  5.83082026e-01 -8.01850680e-02]
 [-4.64852261e-01 -5.43

In [ ]:
#type your code here:
k = 5
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 5
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[ 1.00000000e+00  1.00000000e+00  1.00000000e+00 -7.59907748e-17
   1.00000000e+00]
 [ 3.00000000e+00  4.00000000e+00  5.00000000e+00  1.00000000e+00
   2.49974794e-16]
 [ 4.00000000e+00  4.00000000e+00  4.00000000e+00  1.24364628e-16
   1.00000000e+00]
 [ 4.00000000e+00  5.00000000e+00  4.00000000e+00  1.00000000e+00
   1.00000000e+00]
 [ 4.00000000e+00  6.00000000e+00  4.00000000e+00 -5.18688329e-16
   1.00000000e+00]
 [ 4.00000000e+00  7.00000000e+00  4.00000000e+00  1.00000000e+00
   1.00000000e+00]
 [ 4.00000000e+00  8.00000000e+00  4.00000000e+00 -8.06315470e-16
   1.00000000e+00]
 [ 4.00000000e+00  9.00000000e+00  4.00000000e+00  1.00000000e+00

In [ ]:
#type your code here:
k = 4
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 4
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[ 1.25922885e+00  9.51492408e-01  8.70593425e-01 -1.36648969e-02
   7.86705318e-01]
 [ 3.15132143e+00  3.97168433e+00  4.92446062e+00  9.92023296e-01
  -1.24507961e-01]
 [ 3.78008551e+00  4.04115099e+00  4.10978092e+00  1.15924939e-02
   1.18094665e+00]
 [ 3.90220176e+00  5.01830027e+00  4.04882070e+00  1.00515530e+00
   1.08046884e+00]
 [ 3.97063813e+00  6.00549427e+00  4.01465739e+00  1.54777096e-03
   1.02415908e+00]
 [ 4.09275439e+00  6.98264355e+00  3.95369718e+00  9.95110578e-01
   9.23681266e-01]
 [ 4.16119076e+00  7.96983756e+00  3.91953386e+00 -8.49695197e-03
   8.67371508e-01]
 [ 3.86436371e+00  9.02538062e+00  4.06770939e+00  1.00714988e+00

In [ ]:
#type your code here:
k = 3
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 3
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[ 1.21384154  0.96160619  0.94039684 -0.20890102  0.69940153]
 [ 3.20126712  3.96055479  4.84764664  1.20686756 -0.02843599]
 [ 3.82378874  4.03141247  4.04256754  0.19958445  1.26501107]
 [ 3.78669365  5.04403927  4.2264664   0.50829052  0.85828566]
 [ 4.03173774  5.99187927  3.92068925  0.26437126  1.14168593]
 [ 3.99464265  7.00450607  4.10458811  0.57307732  0.73496053]
 [ 4.23968675  7.95234607  3.79881096  0.32915806  1.0183608 ]
 [ 3.85873252  9.02663544  4.07636989  0.98292697  0.10077039]]
 ---------------------------------------- 

-------------------- A_tildle_rank -------------------- 
 3
 ---------------------------------------- 

-------

In [ ]:
#type your code here:
k = 2
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 2
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[0.97120303 0.97817264 1.17745474 0.14101019 0.2345008 ]
 [3.66822055 3.92867295 4.39143298 0.53346975 0.86625708]
 [3.59876756 4.04677607 4.2624133  0.52408954 0.83386553]
 [3.75757173 5.04602761 4.25491852 0.55028749 0.80248744]
 [3.82442764 6.00603363 4.12323129 0.56333505 0.7444752 ]
 [3.98323181 7.00528516 4.11573651 0.589533   0.71309711]
 [4.05008771 7.96529118 3.98404928 0.60258057 0.65508487]
 [4.1135437  9.00923788 3.82741928 0.61546144 0.58899422]]
 ---------------------------------------- 

-------------------- A_tildle_rank -------------------- 
 2
 ---------------------------------------- 

-------------------- error --------------------

In [ ]:
#type your code here:
k = 1
print("-"* 20, "k", "-" * 20, f"\n {k}\n", "-" * 40, "\n")
print("-"* 20, "A", "-" * 20, f"\n {A}\n", "-" * 40, "\n")
A_tildle = U[:, :k] @ S[:k, :k] @ VT[:k, :]
print("-"* 20, "A_tildle", "-" * 20, f"\n {A_tildle}\n", "-" * 40, "\n")
print("-"* 20, "A_tildle_rank", "-" * 20, f"\n {np.linalg.matrix_rank(A_tildle)}\n", "-" * 40, "\n")
print("-"* 20, "error", "-" * 20, f"\n {np.linalg.norm(A - A_tildle)}\n", "-" * 40, "\n")

-------------------- k -------------------- 
 1
 ---------------------------------------- 

-------------------- A -------------------- 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]
 ---------------------------------------- 

-------------------- A_tildle -------------------- 
 [[0.79493186 1.31209448 0.84185871 0.1173312  0.14945219]
 [3.06849251 5.06477638 3.24963343 0.45290665 0.57689591]
 [3.06469381 5.05850635 3.24561049 0.45234596 0.57618173]
 [3.43143763 5.66384444 3.63400412 0.50647701 0.64513187]
 [3.73797475 6.16980689 3.95863691 0.5517216  0.70276278]
 [4.10471857 6.77514498 4.34703055 0.60585265 0.77171293]
 [4.41125569 7.28110744 4.67166334 0.65109724 0.82934383]
 [4.73965497 7.823155   5.01944886 0.69956867 0.89108496]]
 ---------------------------------------- 

-------------------- A_tildle_rank -------------------- 
 1
 ---------------------------------------- 

-------------------- error --------------------